apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-webapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umarkhaliq-hash/argocd.git
    targetRevision: HEAD
    path: helm-webapp
    helm:
      valueFiles:
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true