apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prestashop-monitor
  labels:
    app: prestashop
spec:
  selector:
    matchLabels:
      app: prestashop
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-monitor
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  endpoints:
  - port: mysql
    interval: 30s