apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ecommerce-frontend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.frontend.port }}
    nodePort: 30090