prestashop:
  image: prestashop/prestashop:8.1
  replicas: 1
  domain: "aed7779ccfd3540c398ebccb04162fb1-1552371232.us-west-2.elb.amazonaws.com"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

mysql:
  image: mysql:8.0
  database: prestashop
  username: prestashop
  password: prestashop123
  rootPassword: root123
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

service:
  type: LoadBalancer