apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: odoo-monitor
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-monitor
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
  - port: postgres
    interval: 30s