prestashop:
  image: prestashop/prestashop:8.1
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

mysql:
  image: mysql:8.0
  database: prestashop
  username: prestashop
  password: prestashop123
  rootPassword: root123
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

service:
  type: NodePort